-- CreateTable
CREATE TABLE "NBA_Data" (
    "player" VARCHAR(255),
    "pos" VARCHAR(2),
    "age" INTEGER,
    "g" INTEGER,
    "gs" INTEGER,
    "mp" DOUBLE PRECISION,
    "fg" DOUBLE PRECISION,
    "fga" DOUBLE PRECISION,
    "fg_percentage" DOUBLE PRECISION,
    "threep" DOUBLE PRECISION,
    "threepa" DOUBLE PRECISION,
    "threep_percentage" DOUBLE PRECISION,
    "twop" DOUBLE PRECISION,
    "twopa" DOUBLE PRECISION,
    "twop_percentage" DOUBLE PRECISION,
    "efg_percentage" DOUBLE PRECISION,
    "ft" DOUBLE PRECISION,
    "fta" DOUBLE PRECISION,
    "ft_percentage" DOUBLE PRECISION,
    "orb" DOUBLE PRECISION,
    "drb" DOUBLE PRECISION,
    "trb" DOUBLE PRECISION,
    "ast" DOUBLE PRECISION,
    "stl" DOUBLE PRECISION,
    "blk" DOUBLE PRECISION,
    "tov" DOUBLE PRECISION,
    "pf" DOUBLE PRECISION,
    "pts" DOUBLE PRECISION,
    "team" VARCHAR(100),
    "birth" VARCHAR(10),
    "college" VARCHAR(255),
    "id" SERIAL NOT NULL,

    CONSTRAINT "NBA_Data_pkey" PRIMARY KEY ("id")
);
